spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:postgresql://localhost:5432/smartfarm?charSet=UTF-8&prepareThreshold=1
        username: "inguk"
        password: "0504"
    redis:
        host: localhost
        port: 6379
        namespace: spring:session
        flush-mode: on-save


jwt:
    header: Authorization
    secret: dai3hufh92h9ueh09333huud3hc8822jajsdi223d4342342fsdnufhsudfy123123y78fe784f9h49273yfihow9dw933984uhfs8dyft4w8
    token-validity-in-seconds: 86400

mybatis:
    mapper-locations: "com.smartFarm.was.web.repository."

logging:level.com.smartfarm: DEBUG


