spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#        org.postgresql.Driver
        url: jdbc:log4jdbc:postgresql://localhost:5432/smartfarm?charSet=UTF-8&prepareThreshold=1
        username: "inguk"
        password: "0504"
    redis:
        host: localhost
        port: 6379

jwt:
    header: Authorization
    secret: "sadnnvjdpj2i29fj3iofnjaajsjd029jej2sd3837fjjajw2JDh2"
    token-validity-in-seconds: 86400

logging:level.com.smartfarm: DEBUG



