package com.smartFarm.was.domain.response;


import lombok.Getter;

@Getter
public enum ResultCode {

    SUCCESS(0, "SUCCESS"),
    FAILED(9999, "FAILED"),
    DENIED(9998, "DENIED"),
    USER_NOT_FOUND(9997, "USER_NOT_FOUND"),
    INVALID_PARAMETER(9996, "INVALID_PARAMETER"),
    PASSWORD_NOT_MATCHED(9995, "PASSWORD_NOT_MATCHED"),
    ID_AND_PW_NOT_MATCHED(9994, "ID_AND_PW_NOT_MATCHED"),
    ALERT_NOT_MATCH_AUTH_NUMBER(9994, "ALERT_NOT_MATCH_AUTH_NUMBER"),
    DUPLICATED_ID(9993, "DUPLICATED_ID"),
    DUPLICATED_TEL(9993, "DUPLICATED_TEL"),
    PAGE_NOT_FOUND(9992, "PAGE_NOT_FOUND"),
    FILE_REQUIRED(9991, "FILE_REQUIRED"),
    ERROR(9990, "ERROR"),
    USER_APP_WITHDRAW(9989, "USER_APP_WITHDRAW"),
    USER_WITHDRAW(9988, "USER_WITHDRAW"),
    RESULT_USER_NOT_FOUND(9987, "RESULT_USER_NOT_FOUND"),
    RESULT_QUANTITY(9986, "RESULT_QUANTITY"),
    RESULT_SALE_ING(9985, "RESULT_SALE_ING"),
    RESULT_ORDER_NOT_FOUND(9984, "RESULT_ORDER_NOT_FOUND"),
    DUPLICATED_REFUND(9983, "DUPLICATED_REFUND");

    private int code;
    private String message;

    ResultCode(int code, String message) {
        this.code = code;
        this.message = message;
    }
}
